# fly.toml app configuration file generated for calc-notes on 2023-07-30T23:06:20+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "calc-notes"
primary_region = "lhr"

[env]
  PORT = "8088"

[http_service]
  internal_port = 8088
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
