GET https://calc-notes.herokuapp.com/api/notes

###
POST https://calc-notes.herokuapp.com/api/notes
Content-Type: application/json

{
    "content": "lol",
    "important": true
}

###
DELETE https://calc-notes.herokuapp.com/api/notes/2

###
GET  http://localhost:3006/api/notes

###
DELETE http://localhost:3006/api/notes/

###
PUT http://localhost:3006/api/notes/5f400fa2c4e120d0dbafc09a
Content-Type: application/json

{
    "content": "I love rest client",
    "important": true
}

###
POST http://localhost:3006/api/notes
Content-Type: application/json

{
    "content": "Fullstack Helsinki is an awesome course",
    "important": true
}