GET https://calc-notes.herokuapp.com/api/notes

###
POST https://calc-notes.herokuapp.com/api/notes
Content-Type: application/json

{
    "content": "I love rest client",
    "important": true
}

###
DELETE https://calc-notes.herokuapp.com/api/notes/2